description = 'Starter for spring based applications handling xfcd data deliveries'

dependencies {
    implementation project(':xfcd-spring-boot-autoconfigure')
        implementation "org.amv.vertx:amv-vertx-spring-boot-starter:${amvVertxVersion}"
    implementation "org.amv.trafficsoft:amv-trafficsoft-rest-client-spring-boot-starter:${trafficsoftRestVersion}"

}
