description = 'A module containing core classes for persisting xfcd data deliveries via jdbc'

dependencies {
    implementation project(':xfcd-consumer-core')

    implementation('com.zaxxer:HikariCP:4.0.3')
    implementation('org.flywaydb:flyway-core:7.15.0')

    implementation("org.springframework.boot:spring-boot-starter-jdbc:${springBootVersion}") {
        exclude module: 'spring-boot-starter-logging'
        exclude module: 'tomcat-jdbc'
    }

    testImplementation 'com.h2database:h2:1.4.196'
    testImplementation ('org.dbunit:dbunit:2.6.0') {
        // postgresql:postgresql:8.4-701.jdbc3 pulls in wrong driver version
        exclude group: 'postgresql', module: 'postgresql'
    }
    testImplementation 'com.github.springtestdbunit:spring-test-dbunit:1.3.0'
}
