description = 'A module containing core classes for persisting xfcd data deliveries with sqlite'

dependencies {
    implementation project(':xfcd-consumer-jdbc')
    implementation "org.springframework.boot:spring-boot-starter-jdbc:${springBootVersion}"
    testImplementation project(':xfcd-consumer-jdbc-test')

    compileOnly 'org.xerial:sqlite-jdbc:3.36.0.3'

    testImplementation("org.amv.trafficsoft:amv-trafficsoft-rest-model-test:${trafficsoftRestVersion}")

    testImplementation project(':xfcd-consumer-jdbc-spring-boot-starter')
    testImplementation 'org.xerial:sqlite-jdbc:3.36.0.3'
    testImplementation 'com.h2database:h2:1.4.196'
    testImplementation ('org.dbunit:dbunit:2.6.0') {
        // postgresql:postgresql:8.4-701.jdbc3 pulls in wrong driver version
        exclude group: 'postgresql', module: 'postgresql'
    }
    testImplementation 'com.github.springtestdbunit:spring-test-dbunit:1.3.0'
    testImplementation 'org.flywaydb:flyway-core:7.15.0'
}
