description = 'A module containing core classes for persisting xfcd data deliveries with postgres'

dependencies {
    implementation project(':xfcd-consumer-jdbc')
    implementation "org.springframework.boot:spring-boot-starter-jdbc:${springBootVersion}"
    testImplementation project(':xfcd-consumer-jdbc-test')

    compileOnly group: 'org.postgresql', name: 'postgresql', version: '42.2.4'

    testImplementation("org.amv.trafficsoft:amv-trafficsoft-rest-model-test:${trafficsoftRestVersion}")

    testImplementation project(':xfcd-consumer-jdbc-spring-boot-starter')
    testImplementation group: 'org.postgresql', name: 'postgresql', version: '42.2.4'
    testImplementation 'com.opentable.components:otj-pg-embedded:0.12.5'

    testImplementation ('org.dbunit:dbunit:2.6.0') {
        // postgresql:postgresql:8.4-701.jdbc3 pulls in wrong driver version
        exclude group: 'postgresql', module: 'postgresql'
    }
    testImplementation 'com.github.springtestdbunit:spring-test-dbunit:1.3.0'
}
