description = 'A module for handling trafficsoft xfcd data deliveries'

dependencies {
    implementation "io.vertx:vertx-rx-java:${vertxVersion}"
    implementation "io.vertx:vertx-reactive-streams:${vertxVersion}"

    implementation "org.amv.trafficsoft:amv-trafficsoft-rest-client-spring-boot-starter:${trafficsoftRestVersion}"
    implementation "org.amv.trafficsoft:amv-trafficsoft-rest-model-test:${trafficsoftRestVersion}"

    implementation 'io.prometheus:simpleclient:0.7.0'

    testImplementation "io.vertx:vertx-unit:${vertxVersion}"
}
