spring.application.name: 'amv-trafficsoft-datahub-demo'
spring.profiles.active: demo

debug: false

server.port: 9000

amv.trafficsoft.api:
  rest:
    baseUrl: 'https://www.example.com'
    username: 'john_doe'
    password: 'mysupersecretpassword'
    contractId: 0

amv.trafficsoft.datahub.xfcd:
  enabled: true
  fetch-interval-in-seconds: 10
  primary-data-store: 'jdbc'

amv.trafficsoft.xfcd.consumer.jdbc:
  enabled: true
  jdbcUrl: jdbc:sqlite:amv-trafficsoft-xfcd-consumer-sqlite.db
  driverClassName: org.sqlite.JDBC
  schemaMigrationEnabled: true
  flywayScriptsLocation: db/migration
