spring.application.name: 'amv-trafficsoft-datahub-demo'
spring.profiles.active: demo

server.port: 8090

amv.trafficsoft.api:
  rest:
    baseUrl: 'https://www.example.com'
    username: 'john_doe'
    password: 'mysupersecretpassword'
    contractId: 0

amv.trafficsoft.datahub.xfcd:
  enabled: true

amv.trafficsoft.xfcd.consumer.jdbc:
  enabled: true
  jdbcUrl: jdbc:sqlite:amv-trafficsoft-xfcd-consumer-sqlite.db
  driverClassName: org.sqlite.JDBC
  schemaMigrationEnabled: true
  flywayScriptsLocation: db/migration
